#=================================================
# https://github.com/P3TERX/Actions-lede
# Description: Build lede using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================
name: lean-x64

on:
  schedule:
    - cron: 0 20 * * *
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
          sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
    - name: Clone source code
      env: 
        REPO_URL: https://github.com/coolsnowwolf/lede
        REPO_BRANCH: dev-master
      run: git clone --depth 1 $REPO_URL -b $REPO_BRANCH lede
    - name: Update feeds
      run: cd lede && ./scripts/feeds update -a

    - name: Install feeds
      run: cd lede && ./scripts/feeds install -a
    
    - name: Costom configure file
      run: |
          cd lede
          rm -f .config
          cp ../x64-master .config
          
    - name: Make Defconfig
      run: |
          cd lede
          make defconfig

    - name: Make download
      run: |
          cd lede
          make download -j8
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;

    - name: Multi-thread compile
      run: |
          cd lede
          echo -e "$(nproc) thread build."
          make -j$(nproc) V=s

    - name: Single-thread compile
      if: failure()
      run: |
          cd lede
          make -j5 V=s

    - name: Assemble artifact
      run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/
          find lede/bin/targets/ -name "*sysupgrade*bin*" | xargs -i mv -f {} ./artifact/
          find lede/bin/targets/ -name "*combined*img*" | xargs -i mv -f {} ./artifact/

    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: lean-x64
        path: ./artifact/

